#ifndef XPGENLIBMOBILE_GLOBAL_H
#define XPGENLIBMOBILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XPGENLIBMOBILE_LIBRARY)
#  define XPGENLIBMOBILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define XPGENLIBMOBILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XPGENLIBMOBILE_GLOBAL_H
